version: '3'
services:
  csharp_app:
    container_name: grifNews
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5177:80
      - 7211:443
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=26032005"
  db:
    container_name: db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=26032005
      - POSTGRES_DB=GrifMVD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}